// Define theme
Theme.set({
	/*
	 * Examples format:
		view: {
			SplashscreenView: {
				// .view.Splashscreen {}
				styles: {backgroundColor: 'orange'}
			},
			// .view {}
			styles: {backgroundColor: 'green'}
		},

		// notice that the first dot is skipped as it is generated by MAF, thus only accepting class names as the first node not ids
		'view > .frame > .text': {
			styles: {backgroundColor: 'green'}
		}
	*/

	SplashscreenView: {
		styles: {
			backgroundColor: '#000',
			backgroundImage: "url('./apps/com.mautilus.app.Dugout/Contents/Images/splash_bg.png')"
		}
	}
});	