// Define theme
Theme.set({
	/*
	 * Examples format:
	 view: {
	 SplashscreenView: {
	 // .view.Splashscreen {}
	 styles: {backgroundColor: 'orange'}
	 },
	 // .view {}
	 styles: {backgroundColor: 'green'}
	 },

	 // notice that the first dot is skipped as it is generated by MAF, thus only accepting class names as the first node not ids
	 'view > .frame > .text': {
	 styles: {backgroundColor: 'green'}
	 }
	 */

	SplashscreenView: {
		styles: {
			backgroundColor: '#000',
			backgroundImage: "url('./apps/com.mautilus.app.Dugout/Contents/Images/splash_bg.png')"
		}
	},

	splashLogo: {
		styles: {
			vOffset: 297,
			hOffset: 446
		}
	},

	'splashLogo.hidden': {
		styles: {
			opacity: 0
		}
	},

	PodiumView: {
		styles: {
			backgroundImage: 'url("./apps/com.mautilus.app.Dugout/Contents/Images/score_bg.png")'
		}
	},

	'imgPodium.position1': {
		styles: {
			top: '211px',
			left: '1276px'
		}
	},

	'imgPodium.position2': {
		styles: {
			top: '285px',
			left: '1041px'
		}
	},

	'imgPodium.position3': {
		styles: {
			top: '359px',
			left: '811px'
		}
	},

	'imgPodium.position4': {
		styles: {
			top: '432px',
			left: '582px'
		}
	},

	'podiumText': {
		styles: {
			'display': 'inline-block',
			'font-size': '26px',
			'line-height': '45px',
			'background-color': 'rgba(255,255,255, 0.6)',
			'border-radius': '30px',
			'width': '220px',
			'color': '#000000',
			'text-align': 'center',
			'box-shadow': ' 2px 4px 0 rgba(0, 0, 0, 0.1), 0 5px 23px 0 rgba(0, 0, 0, 0.05)'
		}
	},

	'winner': {
		styles: {
			'top': '120px',
			'left': '554px',
			'display': 'inline-block',
			'font-size': '26px',
			'line-height': '45px',
			'background-color': 'rgba(255,255,255, 0.6)',
			'border-radius': '30px',
			'width': '917px',
			'color': '#000000',
			'text-align': 'center',
			'font-weight': 'bold',
			'box-shadow': ' 2px 4px 0 rgba(0, 0, 0, 0.1), 0 5px 23px 0 rgba(0, 0, 0, 0.05)'
		}
	},

	'podiumText.name': {
		styles: {
			'font-weight': 'bold',
			'top': '782px'
		}
	},

	'podiumText.score': {
		styles: {
			'top': '832px'
		}
	},

	'podiumText.name.position1': {
		styles: {
			left: '1248px'
		}
	},

	'podiumText.name.position2': {
		styles: {
			left: '1018px'
		}
	},

	'podiumText.name.position3': {
		styles: {
			left: '788px'
		}
	},

	'podiumText.name.position4': {
		styles: {
			left: '558px'
		}
	},

	'podiumText.score.position1': {
		styles: {
			left: '1248px'
		}
	},

	'podiumText.score.position2': {
		styles: {
			left: '1018px'
		}
	},

	'podiumText.score.position3': {
		styles: {
			left: '788px'
		}
	},

	'podiumText.score.position4': {
		styles: {
			left: '558px'
		}
	},

	HomeView: {
		styles: {
			backgroundColor: '#000',
			backgroundImage: "url('./apps/com.mautilus.app.Dugout/Contents/Images/splash_bg.png')"
		}
	},

	'HomeView-wrapper': {
		styles: {
			height: 1080,
			width: 1920
		}
	},

	'HomeView-wrapper-logo': {
		styles: {
			vOffset: 100,
			hOffset: 739.5
		}
	},

	'HomeView-wrapper-playersWrapper': {
		styles: {
			vOffset: 450,
			hOffset: 460,
			height: 350,
			width: 1000
		}
	},

	'HomeView-wrapper-playersWrapper-row': {
		styles: {
			height: 75,
			width: 1000,
			backgroundColor: 'rgba(255,255,255, .7)',
			hOffset: 0,
			'border-radius': '75px',
			'box-shadow': ' 2px 4px 0 rgba(0, 0, 0, 0.1), 0 5px 23px 0 rgba(0, 0, 0, 0.05)'
		}
	},

	'HomeView-wrapper-playersWrapper-row.row1': {
		styles: {
			vOffset: 0
		}
	},

	'HomeView-wrapper-playersWrapper-row.row2': {
		styles: {
			vOffset: 90
		}
	},

	'HomeView-wrapper-playersWrapper-row.row3': {
		styles: {
			vOffset: 180
		}
	},

	'HomeView-wrapper-playersWrapper-row.row4': {
		styles: {
			vOffset: 270
		}
	},

	'HomeView-wrapper-playersWrapper-row .image.worm': {
		styles: {
			width: 70,
			height: 85,
			display: 'block'
		}
	},

	'HomeView-wrapper-playersWrapper-row .image.worm.red': {
		styles: {
			'content': 'url(./apps/com.mautilus.app.Dugout/Contents/Images/cervik_red.png)'
		}
	},

	'HomeView-wrapper-playersWrapper-row .image.worm.green': {
		styles: {
			'content': 'url(./apps/com.mautilus.app.Dugout/Contents/Images/cervik_green.png)'
		}
	},

	'HomeView-wrapper-playersWrapper-row .image.worm.yellow': {
		styles: {
			'content': 'url(./apps/com.mautilus.app.Dugout/Contents/Images/cervik_yellow.png)'
		}
	},

	'HomeView-wrapper-playersWrapper-row .image.worm.blue': {
		styles: {
			'content': 'url(./apps/com.mautilus.app.Dugout/Contents/Images/cervik_blue.png)'
		}
	},

	'HomeView-wrapper-playersWrapper-row .text': {
		styles: {
			'text-align': 'center',
			width: '100%',
			'line-height': '75px',
			'font-size': '36px',
			color: '#ccc'
		}
	},

	'HomeView-wrapper-playersWrapper-row .text.connected': {
		styles: {
			color: '#aaa'
		}
	},

	'HomeView-wrapper-playersWrapper-row .text.ready': {
		styles: {
			color: '#000'
		}
	},

	PlaygroundView: {
		styles: {
			backgroundImage: 'url("./apps/com.mautilus.app.Dugout/Contents/Images/ingame/ingame_bg.png")'
		}
	},

	'scoreBackground': {
		styles: {
			'width': '1920px',
			'height': '130px',
			'background-color': 'rgba(0, 0, 0, 0.5)'
		}
	},

	'leftBackground': {
		styles: {
			'top': '130px',
			'width': '70px',
			'height': '900px',
			'background-color': 'rgba(0, 0, 0, 0.5)'
		}
	},

	'rightBackground': {
		styles: {
			'top': '130px',
			'left': '1850px',
			'width': '70px',
			'height': '900px',
			'background-color': 'rgba(0, 0, 0, 0.5)'
		}
	},

	'bottomBackground': {
		styles: {
			'top': '1030px',
			'width': '1920px',
			'height': '1080px',
			'background-color': 'rgba(0, 0, 0, 0.5)'
		}
	},

	'ingameText': {
		styles: {
			'display': 'inline-block',
			'top': '60px',
			'font-size': '22px',
			'line-height': '35px',
			'background-color': 'rgba(255,255,255, 0.6)',
			'border-radius': '30px',
			'width': '240px',
			'color': '#000000',
			'text-align': 'left',
			'padding-left': '70px',
			'box-shadow': ' 2px 4px 0 rgba(0, 0, 0, 0.1), 0 5px 23px 0 rgba(0, 0, 0, 0.05)',
			'z-index': '5'
		}
	},

	'ingameText.name.position1': {
		styles: {
			left: '88px'
		}
	},

	'ingameText.name.position2': {
		styles: {
			left: '358px'
		}
	},

	'ingameText.name.position3': {
		styles: {
			left: '628px'
		}
	},

	'ingameText.name.position4': {
		styles: {
			left: '898px'
		}
	},

	'imgScore': {
		styles: {
			'top': '45px',
			'z-index': '6'
		}
	},

	'imgScore.position1': {
		styles: {
			left: '82px'
		}
	},

	'imgScore.position2': {
		styles: {
			left: '352px'
		}
	},

	'imgScore.position3': {
		styles: {
			left: '622px'
		}
	},

	'imgScore.position4': {
		styles: {
			left: '892px'
		}
	},

	'canvasFirst': {
		styles: {
		}
	}
	
});	